name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache (NDK)
        uses: actions/cache@v2
        with:
          path: ${ANDROID_HOME}/ndk/20.0.5594570
          key: ndk-cache

      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install 'ndk;20.0.5594570'

      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build  --stacktrace --info
      - name: Build Debug APK
        run: ./gradlew assembleDebug
